### PR TITLE
Issue 626 drug mechanism of action semantics

### PR DESCRIPTION
**Pull request by RichardBruskiewich**
(Partial) resolution of Issue #626 - Drug "Mechanism of Action"

### CODE REVIEW

**Comment by cbizon** [comment]
So I think that this is a new category, but I do not understand what would populate it.

**Comment by RichardBruskiewich** [comment]
> So I think that this is a new category, but I do not understand what would populate it.

Iterating @cbizon ... see issue #626

**Comment by sierra-moxon** [comment]
@RichardBruskiewich  - do you think we can draft this PR or close it with the work you and @mbrush and @vdancik are doing with the chemical working group?  :)

**Comment by sierra-moxon** [comment]
@RichardBruskiewich - this was discussed along with ticket #626 in the chemical working group meeting.  The general consensus was that mechanism of action would be modeled using qualifiers.  I'll let @vdancik round out the ticket summary on #626.  Closing for now - please reopen or comment on the ticket if you feel strongly about this modeling! :)

**Pull request closed without merging**
