### PR TITLE
Issue 83 biolinkml

### PR DESCRIPTION
**Pull request by hsolbrig**
Do not merge this yet -- @cmungall  - how do we determine whether there isn't anything in here that breaks downstream code?

Also, when we DO pull this, we need to create a new pypi release.

### CODE REVIEW

**Comment by cmungall** [comment]
@hsolbrig just looking back at past tickets. This is a PR with >600 files changed. Was this intentional?

@deepakunni3 @RichardBruskiewich can this be closed?

**Comment by RichardBruskiewich** [comment]
> 
> 
> @hsolbrig just looking back at past tickets. This is a PR with >600 files changed. Was this intentional?
> 
> @deepakunni3 @RichardBruskiewich can this be closed?

No idea. @hsolbrig's the best authority for this one.

**Comment by deepakunni3** [comment]
@cmungall This is because majority of the files here are markdown files, which we do not commit to `master` anymore.

Also, this is a PR from January. Biolinkml has evolved since then and is at v1.5.4

I vote for this to be closed.

**Comment by hsolbrig** [comment]
Correct to close this.  This was updating the build file to use a later (now ancient) version of biolinkml

**Pull request closed without merging**
