### PR TITLE
Added UMLS Semantic Types and Codes to the Biolink YAML model

### PR DESCRIPTION
**Pull request by RichardBruskiewich**
Completing https://github.com/biolink/biolink-model/issues/7#issuecomment-475267073

### CODE REVIEW

**Comment by cmungall** [comment]
any idea why build is failing? @hsolbrig may be able to help

sorry to make you do busy work, the idea was to map to the closest in the UMLSST hierarchy, no need to include subclasses / narrow mappings

**Comment by hsolbrig** [comment]
The unit tests currently report any differences in outputs, so any changes require that the output changes be reviewed and updated.  Should have this problem addressed in the next week or so -- moving the modeling language to a separate project so we can differentiate breaking changes to the language itself from expected changes to the model.   Will do the checkout/make cycle on this request later today

**Comment by RichardBruskiewich** [comment]
@cmungall, at the end of the day, the "busy work" was not too tedious. i was pretty systematic about compiling things in a worksheet before adding them in, one major semantic group at a type, splitting off some of the semantic types into other categories when it made sense.

I did, however, do a YAML compliant # documentation of semantic types under the "mappings" tags, where it seemed helpful, but perhaps, this messes up the parsing of the model, hence, the Travis test failures.

**Comment by hsolbrig** [comment]
Interesting question about the URI to use for the semantic net.  We discussed UMLS URI's with the NLM several years back and, while we reached a consensus, I don't believe that the NLM ever implemented them.  I'll ping Olivier Bodenrider and get back to you on this.

**Comment by hsolbrig** [comment]
If it is ok with everyone, I would like to merge this pull request and address the remaining issues inline.  (That is one of the other problems with this current setup is that changes in the model result in changes in ALL of the target representations.  Merging the yaml changes is simple, merging all of the UML models, context.jsonld, etc, etc. can be a daunting task...

**Comment by hsolbrig** [comment]
Merging so I can generate all of the secondary artifacts.

**Pull request merged**
