### PR TITLE
Prepare for pypi release

### PR DESCRIPTION
**Pull request by deepakunni3**
FYI @cmungall @hsolbrig

### CODE REVIEW

**Comment by deepakunni3** [comment]
How are the contents of `_site/` folder updated? Are they just copied over from top-level?

**Comment by hsolbrig** [comment]
What `_site/` folder are you referencing in the above question?

**Comment by deepakunni3** [comment]
@hsolbrig My mistake. It's a Jekyll folder. 
But it is part of `.gitignore`, so I shouldn't be worrying about it.

**Comment by hsolbrig** [comment]
Why the changes to setup.py?

**Comment by hsolbrig** [comment]
Wouldn't it make more sense to change `setup.cfg` to
```
[metadata]
name = biolink_model
description = 'A high level datamodel of biological entities and associations'
url = https://github.com/biolink/biolink-model
author = Harold Solbrig
author-email = solbrig@jhu.edu
summary = Biolink Model
home-page = https://biolink.github.io/biolink-model/docs/
license = CC0 1.0 Universal
python-requires = >=3.7
classifier =
    Development Status :: 4 - Beta
    Environment :: Console
    Intended Audience :: Developers
    Intended Audience :: Science/Research
    Intended Audience :: Healthcare Industry
    License :: CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: 3.6
    Programming Language :: Python :: 3.7
keywords =
    biolink
    model
```

And leave `setup.py` as is?   The commands for creating a pypi distro are:

1)  Commit all pending changes (if there are uncommitted changes, `pbr` builds a "-dev" distro...)
2)  Create a new tag:
`git tag v0.0.1`
3)  Generate the distro:
`python setup.py bdist_wheel`
4) Submit the distro w/ twine:
`twine upload dist/biolink_model-0.0.1-py3-none-any.whl`

**Comment by deepakunni3** [comment]
@hsolbrig I was having trouble building a distribution from contents of a single folder via `setup.cfg`. It seemed to work when I specify the folder in `setup.py`

Do you have any recommendations?

**Pull request merged**
