### PR TITLE
Adding a gene to gene co-expression association

### PR DESCRIPTION
**Pull request by cmungall**
Adding ﻿ gene to gene co-expression association
See #324

### CODE REVIEW

**Comment by cbizon** [comment]
I don't like having the same entity (here an anatomy or a phenotype) appear as the value of an edge property when it is also likely to appear in a graph as node.  Gene expression or coexpression is inherently an n-ary problem, and I think we should address that generically.

**Comment by deepakunni3** [comment]
@cbizon @cmungall Is this discussion still on-going?

**Comment by cbizon** [comment]
Seems like the best current solution is to do what @cmungall proposed - having edges with properties for tissue etc.   I think we would want to apply the same pattern to eQTL (variant -[affect expression of]->gene) edges.  

I do think that there's room for incorporating information like this into a bigger discussion about n-ary and contextual nodes.  

One way of thinking about this might be modeling eqtls or co-expression with CAMs?

**Comment by RichardBruskiewich** [comment]
> Seems like the best current solution is to do what @cmungall proposed - having edges with properties for tissue etc. I think we would want to apply the same pattern to eQTL (variant -[affect expression of]->gene) edges.

@cbizon I'm taking a run at this. Check back here tomorrow.

**Review by deepakunni3 — APPROVED** [review]

**Comment by deepakunni3** [comment]
@cbizon Would be great to have your feedback on this PR

**Comment by cbizon** [comment]
Everything here makes sense to me and looks good.  The only thing that I'm not sure about is whether there is a co-expression predicate?  I see the association, but that's different, right?

**Comment by cmungall** [comment]
I'm going to go ahead and merge as it doesn't break any compatibility, but I agree with @cbizon 
> I do think that there's room for incorporating information like this into a bigger discussion about n-ary and contextual nodes.

Moved here: #566

**Pull request merged**
