### PR TITLE
Representing dataset metadata in BioLink Model

### PR DESCRIPTION
**Pull request by deepakunni3**
Dataset metadata model adapted from HCLS by @justaddcoffee

graphviz

### CODE REVIEW

**Comment by justaddcoffee** [comment]
+1 
note that the diagram above is a small subset of the triples required for HCLS compliance. (Not necessarily a goal here, just saying...)

**Comment by deepakunni3** [comment]
An update to the above GraphViz:
graphviz (1)

Related graphviz snippet:
```
digraph metadata_model {
    { rank=min "dctypes:Dataset"}
    { rank=min summary_level }
    { rank=BH; version_level distribution_level }

    summary_level [style=filled, fillcolor=grey] 
    version_level [style=filled, fillcolor=grey] 
    distribution_level [style=filled, fillcolor=grey] 

    download_date1 [shape=box]
    download_date2 [shape=box]
    1234567 [shape=box]
    345678 [shape=box]
    download_version_number [shape=box]
    ingest_date [shape=box]
    
    summary_level -> source_web_page_url [label="dct:source", style=dashed];
    summary_level -> source_logo_url [label="schema:logo", style=dashed];
    summary_level -> "dctypes:Dataset"[label="rdf:type"]
    
    version_level -> summary_level [label="dct:isVersionOf"];
    version_level -> distribution_level [label="dct:distribution"];
    version_level -> ingest_date [label="pav:version"];
    version_level -> source_file1 [label="dct:source", style=dashed];
    version_level -> source_file2 [label="dct:source", style=dashed];
    version_level -> "dctypes:Dataset"[label="rdf:type"]

    source_file1 -> download_date1 [label="pav:version"];
    source_file2 -> download_date2 [label="pav:version"]
    source_file2 -> download_version_number [label="pav:version"];

    distribution_level -> monarch_source_ttl [label="dcat:downloadURL"];
    distribution_level -> monarch_source_ntriples [label="dcat:downloadURL"];
    distribution_level -> 1234567 [label="void:triples"];
    distribution_level -> 345678 [label="void:distinctSubjects"];
    distribution_level -> "dctypes:Dataset"[label="rdf:type"]
}
```

Things to note:
- is there a predicate better than `pav:version` that can be used to refer to download date?
- Add `version_label pav:createdOn ingest_date` to also capture the creation date of this version of the dataset

**Comment by justaddcoffee** [comment]
Looks good Deepak! 

> is there a predicate better than pav:version that can be used to refer to download date?

Yes, I recommend pav:retrievedOn for this. Previously Dipper conflated download date and version numbers based on date/timestamps, and it caused a lot of confusion. 

Also, my diagram contained an error - there should be two separate distribution levels, one for the turtle distribution and one for ntriples distribution. So, I humbly suggest the updated diagram, attached. Graphviz code below:

graphviz_jr

```
digraph metadata_model {
    { rank=min "dctypes:Dataset"}
    { rank=min summary_level }
    { rank=BH; version_level distribution_level_format1 distribution_level_format2 }

    summary_level [style=filled, fillcolor=grey] 
    version_level [style=filled, fillcolor=grey] 
    distribution_level_format1 [style=filled, fillcolor=grey] 
    distribution_level_format2 [style=filled, fillcolor=grey] 

    download_date1 [shape=box]
    download_date2 [shape=box]
    1234567 [shape=box]
    345678 [shape=box]
    2345678 [shape=box] 
    456789 [shape=box] 
    download_version_number [shape=box]
    ingest_date [shape=box]
    
    summary_level -> source_web_page_url [label="dct:source", style=dashed];
    summary_level -> source_logo_url [label="schema:logo", style=dashed];
    summary_level -> "dctypes:Dataset"[label="rdf:type"]
    
    version_level -> summary_level [label="dct:isVersionOf"];
    version_level -> distribution_level_format1 [label="dct:distribution"];
    version_level -> distribution_level_format2 [label="dct:distribution"];
    version_level -> ingest_date [label="pav:version"];
    version_level -> source_file1 [label="dct:source", style=dashed];
    version_level -> source_file2 [label="dct:source", style=dashed];
    version_level -> "dctypes:Dataset"[label="rdf:type"]

    source_file1 -> download_date1 [label="pav:retrievedOn"];
    source_file2 -> download_date2 [label="pav:retrievedOn"]
    source_file2 -> download_version_number [label="pav:version"];

    distribution_level_format1  -> monarch_source_ntriples [label="dcat:downloadURL"];
    distribution_level_format1  -> 1234567 [label="void:triples"];
    distribution_level_format1  -> 345678 [label="void:distinctSubjects"];
    distribution_level_format1  -> "dctypes:Dataset"[label="rdf:type"]
    
    distribution_level_format2 -> monarch_source_ttl [label="dcat:downloadURL"];
    distribution_level_format2 -> 2345678 [label="void:triples"];
    distribution_level_format2 -> 456789 [label="void:distinctSubjects"];
    distribution_level_format2 -> "dctypes:Dataset"[label="rdf:type"]
}
```

**Comment by diatomsRcool** [comment]
One thing I just remembered is that in order to get the tests to work I had to copy the biolink module folder and the yaml file into the tests directory.

**Comment by diatomsRcool** [comment]
@deepakunni3 is the GraphViz something I should have changed?

**Comment by deepakunni3** [comment]
@diatomsRcool No, I am just using the graphviz to update how the metadata model should look like.

**Comment by hsolbrig** [comment]
What is the purpose of the change in biolink/__init__.py?  Does os.path.join actually return `Union[bytes, str]`?  Given that this is true and this is needed, why not use the post 3.6 syntax:
`BIOLINK_MODEL_YAML: Union[bytes, str] = os.path.join(basedir, 'biolink-model.yaml')`

**Comment by diatomsRcool** [comment]
@hsolbrig I don't recall making that change specifically, but it probably had to do with me trying to figure out why the tests wouldn't run. The fix I found was to copy and paste the biolink folder and the yaml file into the tests directory.

**Pull request merged**
