### PR TITLE
domain/range on directly interacts with

### PR DESCRIPTION
**Pull request by cbizon**
domain and range on this predicate are currently named thing, I think, but the description states that they should be molecular entities.

### CODE REVIEW

**Comment by cbizon** [comment]
Data Modeling call: Decision is that this might be too restrictive.  To make sure that we don't cause problems, we want to interrogate the metaKG and find out how this edge is being used before doing anything concrete.

**Comment by deepakunni3** [comment]
@cbizon  Was there a decision made after investigating the metaKG?

**Comment by cbizon** [comment]
The metaKG doesn't show any instances of this predicate, and the only ones in /predicates endpoints are mine :) 

Those are all being used as chemical-gene edges.

So I think we have a free hand here.

**Review by sierra-moxon — APPROVED** [review]

**Review by deepakunni3 — APPROVED** [review]

**Comment by deepakunni3** [comment]
Thanks for confirming :+1:

**Pull request merged**
