### PR TITLE
Issue 572 attribute url

### PR DESCRIPTION
**Pull request by RichardBruskiewich**
Deprecating `iri` slot usage, in favor of `url` slot in `biolink:Attribute`.  Resolves  issue #572

### CODE REVIEW

**Comment by RichardBruskiewich** [comment]
Chris has suggested some alterations that depart from TRAPI Attribute schema properties. I'll make those changes but perhaps this can be discussed on the next data modelling call, in the context of TRAPI Attribute discussions which will take place tomorrow?

**Comment by RichardBruskiewich** [comment]
@mbrush I used  @cmungall's  suggested name `primary web url`  for the field.

**Comment by deepakunni3** [comment]
I think calling it *primary* means that there is only one authoritative URL for an entity. 

We want to be able to capture 0, 1 or more URLs that further describes an entity. These URLs may be RDF resource URLs or webpages. Perhaps its easier to just name it `web url`?

**Comment by RichardBruskiewich** [comment]
> 
> 
> I think calling it _primary_ means that there is only one authoritative URL for an entity.
> 
> We want to be able to capture 0, 1 or more URLs that further describes an entity. These URLs may be RDF resource URIs or webpages. Perhaps its easier to just name it `web url`?

Is not a url always on the web? Thus, `web url` is even a bit redundant a name.    I wonder if `reference url` may be more helpful here (if we don't want to simply use `url`)?

**Review by cmungall — CHANGES_REQUESTED** [review]
`web url` is redundant. just name it url

also add mapping to https://schema.org/url

**Comment by sierra-moxon** [comment]
@RichardBruskiewich - I think I should close this PR?  The original concerns from Matt (probably) are addressed by the infores and EPC work in the mix (and cover a slightly different use case than a simple IRI).  Please, of course, reopen if I summarized incorrectly.

**Pull request closed without merging**
