### PR TITLE
Mark relationships as symmetric where appropriate

### PR DESCRIPTION
**Pull request by patrickkwang**
Add `symmetric: true` to:
* `in linkage disequilibrium with`
* `related condition`
* `directly interacts with`
* `temporally related to`
* `overlaps`
* `chemically similar to`
* `coexpressed with`
* `correlated with`
* `positively correlated with`
* `negatively correlated with`
* `colocalizes with`
* `in cell population with`
* `in complex with`
* `in pathway with`
* `coexists with`
* `xenologous to`
* `orthologous to`
* `paralogous to`
* `homologous to`
* `genetically interacts with`
* `molecularly interacts with`
* `close match`
* `exact match`
* `same as`

### CODE REVIEW

**Review by deepakunni3 — APPROVED** [review]
Looks great! Thanks for adding the symmetric tags

**Comment by deepakunni3** [comment]
@patrickkwang Is this ready to merge or did you have more additions?

**Comment by patrickkwang** [comment]
I feel _pretty_ confident that this is all of them, but someone with more experience could confirm that all of the remaining relationships are directed.

**Comment by deepakunni3** [comment]
Looks great! Thanks for the PR!

**Pull request merged**
